### ISSUE TITLE
TestUtils can't connect to db. 

### ISSUE THREAD

**Issue by fuubi** [bimgur/bimgur#8]
# Error message, crashes while initializing process engine. Can't connect to db.

`13:52:19.558 [main] ERROR org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl - Exception while initializing Database connection
org.postgresql.util.PSQLException: FATAL: Passwort-Authentifizierung für Benutzer »bimgur« fehlgeschlagen (pgjdbc: autodetected server-encoding to be ISO8859_1, if the message is not readable, please check database logs and/or host, port, dbname, user, password, pg_hba.conf)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:443) ~[postgresql-9.4.1212.jar:9.4.1212]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:217) ~[postgresql-9.4.1212.jar:9.4.1212]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52) ~[postgresql-9.4.1212.jar:9.4.1212]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216) ~[postgresql-9.4.1212.jar:9.4.1212]
	at org.postgresql.Driver.makeConnection(Driver.java:404) ~[postgresql-9.4.1212.jar:9.4.1212]
	at org.postgresql.Driver.connect(Driver.java:272) ~[postgresql-9.4.1212.jar:9.4.1212]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_111]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_111]
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:201) ~[mybatis-3.3.0.jar:3.3.0]
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:196) ~[mybatis-3.3.0.jar:3.3.0]
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:93) ~[mybatis-3.3.0.jar:3.3.0]
	at org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:385) ~[mybatis-3.3.0.jar:3.3.0]
	at org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:89) ~[mybatis-3.3.0.jar:3.3.0]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.initDatabaseType(ProcessEngineConfigurationImpl.java:853) ~[activiti-engine-5.21.0.jar:5.21.0]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.initDataSource(ProcessEngineConfigurationImpl.java:803) ~[activiti-engine-5.21.0.jar:5.21.0]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.init(ProcessEngineConfigurationImpl.java:619) ~[activiti-engine-5.21.0.jar:5.21.0]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:607) ~[activiti-engine-5.21.0.jar:5.21.0]
	at ch.fhnw.ima.bimgur.activiti.TestUtils.processEngine(TestUtils.java:22) ~[test/:?]
	at ch.fhnw.ima.bimgur.activiti.service.RepositoryServiceTest.beforeEach(RepositoryServiceTest.java:19) ~[test/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:289) ~[junit-platform-commons-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:114) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeMethodInTestExtensionContext(ClassTestDescriptor.java:280) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$10(ClassTestDescriptor.java:266) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.lambda$null$3(MethodTestDescriptor.java:177) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(MethodTestDescriptor.java:197) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.invokeBeforeEachMethods(MethodTestDescriptor.java:176) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:151) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:63) ~[junit-jupiter-engine-5.0.0-M3.jar:5.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:80) ~[junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76) ~[junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:87) ~[junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76) ~[junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:87) ~[junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) [junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76) [junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51) [junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43) [junit-platform-engine-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:129) [junit-platform-launcher-1.0.0-M3.jar:1.0.0-M3]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85) [junit-platform-launcher-1.0.0-M3.jar:1.0.0-M3]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:42) [junit5-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84) [junit-rt.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:?]`

**Comment by fuubi** [comment]
### When running integration test bind docker psql port 5432 to local machine port 5433


`docker run -p 8080:8080 -p 5433:5432 bimgur`
